### ISSUE TITLE
const used in strict mode

### ISSUE THREAD

**Issue by frob** [cilice/markdown-cli#6]
```
markdown-cli README.md 
/usr/local/lib/node_modules/markdown-cli/cli.js:4
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by cilice** [comment]
I've actually overlooked that someone might create an issue there :) Sorry! Could you try now?
